### ISSUE TITLE
Sprunk Drop

### ISSUE THREAD

**Issue by nottherealtar** [hexarobi/stand-lua-sprunkstop#1]
Sprunk drop (Single Can) gives out an error. Dont have the error at hand but just wanted to let you know.
Also can i suggest a refill feature for sprunk cans that doesnt involve vending machines ? would be nice to use the lua to afk the votes :D

**Comment by hexarobi** [comment]
Thanks for the feedback! =) I pushed a fix for the sprunk drop bug a few hours ago, if you re-run the script it should auto-update and fix that. I'm not sure I can reset the vending machine limit, but maybe could teleport to the diff machines on the map. =)

**Comment by nottherealtar** [comment]
Thank You! I loved the sprunk theme lua and would appreciate the vending teleport feature alot, that + the purchase loop would make a heck of a convenience!
